# Docker Compose para usar solo con Neon (PostgreSQL externo)
# Usa este archivo si ya tienes tu BD en Neon
version: '3.8'

services:
  api:
    build: .
    container_name: task-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
