"""Initial migration: users and tasks tables

Revision ID: af02fba88cf2
Revises: 
Create Date: 2025-10-05 10:20:59.078275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af02fba88cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columnas nuevas
    op.add_column('tasks', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    
    # Actualizar registros existentes con valores por defecto
    op.execute("UPDATE tasks SET status = 'planificado' WHERE status IS NULL")
    
    # Ahora hacer la columna NOT NULL
    op.alter_column('tasks', 'status', nullable=False, server_default='planificado')
    
    # Crear índices
    op.create_index(op.f('ix_tasks_category'), 'tasks', ['category'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_start_date'), 'tasks', ['start_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_start_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category'), table_name='tasks')
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
